import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar_main from "./navbar/navbar_main";
import StyledComponentsRegistry from "./lib/AntdRegistry";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-Oswald",
});
config.autoAddCss = false;
export const metadata: Metadata = {
  title: "Footuane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          components: {
            Table: {
              cellPaddingBlock: 4,
              cellPaddingInlineMD: 4,
              headerBg: "#a66cff",
              headerColor: "#ffffff",
              rowSelectedBg: "#a66cff",
            },
          },
          token: {
            fontFamily: "var(--font-Oswald)",
          },
        }}
      >
        <body
          className={inter.className + " bg-primary-white " + inter.variable}
        >
          <StyledComponentsRegistry>
            <Navbar_main />
            <div className="container mx-auto">{children}</div>
          </StyledComponentsRegistry>
        </body>
      </ConfigProvider>
    </html>
  );
}
