export const leaguesIds: Record<string, number> = {
  "UEFA Champions League": 2,
  "English Premier League": 39,
  "La Liga (Spain)": 140,
  "Bundesliga (Germany)": 78,
  "Serie A (Italy)": 135,
  "Ligue 1 (France)": 61,
  "Pro League (ksa)": 307,
  "Copa Libertadores": 5,
  "UEFA Europa League": 3,
  "Copa del Rey (Spain)": 143,
  "DFB-Pokal (Germany)": 81,
  "Botola Pro (Morocco)": 200,
  "Premier League (Egypt)": 233,
  "FA Cup (England)": 45,
  "Coppa Italia (Italy)": 137,
  "Brasileirão Serie A (Brazil)": 71,
  "Liga Profesional (Argentina)": 128,
  "MLS All-Star (USA)": 866,
  "Portuguese Primeira Liga (Portugal)": 94,
  "Chinese Super League (CSL)": 169,
  "Russian Premier League (Russia)": 235,
  "K-League 1 (South Korea)": 660,
  "J1 League (Japan)": 98,
  "Scottish Premiership (Scotland)": 179,
  "A-League (Australia)": 188,
  "Belgian Pro League (Belgium)": 144,
  "Turkish Süper Lig (Turkey)": 203,
  "Swiss Super League (Switzerland)": 207,
  "Mexican Liga MX (Mexico)": 262,
  "South African Premier Division": 288,
  "Qatar Stars League (Qatar)": 305,
  "Indian Super League (ISL)": 323,
  "United Arab Emirates Pro League (UAE)": 301,
};

export const statusShorts: Record<string, string> = {
  in_play: "1H-2H-ET-BT-SUSP-INT-LIVE",
  first_half: "HT",
  break_time: "BT",
  scheduled: "TBD-NS",
  finished: "FT-AET-PEN",
  penalty: "P",
};
